### ISSUE TITLE
if you resize the window the pickaxe gets a weird offset.

### ISSUE THREAD

**Issue by NGSpace** [Nabir14/MinecraftCave#1]

**Comment by Nabir14** [comment]
Yeah I see it's kinda weird I will make it so it can't be resized or full screen. So it can't cause any weird errors.

**Comment by Nabir14** [comment]
I have fixed the window resize problem and I also added icon. I also added instructions on README.md to help you compile and run the program. Sorry for being late I was busy on other projects.
